---
include:
  - board: nice_nano_v2
    shield: corne_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2
    shield: corne_peripheral_left

  - board: nice_nano_v2
    shield: corne_peripheral_right

  - board: nice_nano_v2
    shield: settings_reset
